// pages/posts/[slug].tsx
import { getAllPosts, getPost, writePostsSpecToFS } from "lib";
import type { GetStaticProps, GetStaticPaths } from "next";

import React from "react";
import { HomeButton, Body } from "components";
import Image from "next/image";
import { NextSeo } from "next-seo";
import { useUrl, seoData, defaultSection } from "utils";

type PostProps = {
  meta: PostMetadata;
  content: string;
};

const Post: React.FC<PostProps> = ({
  meta: { title, cover, date, published, readTime, description, tags, author },
  content,
}) => {
  const { url, resolvedPath: coverImage } = useUrl(cover);

  return (
    <div itemScope itemType="https://schema.org/TechArticle">
      <NextSeo
        {...seoData}
        title={title}
        description={description}
        additionalMetaTags={[
          ...seoData.additionalMetaTags!,
          { name: "image", content: coverImage ?? "" },
          { name: "keywords", content: tags?.join(",") ?? "" },
        ]}
        canonical={url}
        openGraph={{
          ...seoData.openGraph,
          title,
          url,
          description,
          type: "article",
          images: coverImage
            ? [{ url: coverImage, alt: "Article Cover" }]
            : undefined,
          article: {
            publishedTime: date,
            authors: [author],
            section: defaultSection,
            tags,
          },
        }}
      />
      <header>
        <div className="relative overflow-hidden text-center text-white max-h-cover min-h-cover">
          <div className="absolute inset-x-0 bottom-0 z-10 max-w-xl px-6 pb-16 mx-auto text-center md:max-w-3xl xl:max-w-4xl text-shadow-lg">
            <p className="text-sm uppercase">{readTime}</p>
            <h1 itemProp="headline">{title}</h1>
            <p itemProp="datePublished">{published}</p>
          </div>
          {cover && (
            <Image
              className="filter-blur"
              src={cover}
              alt="Post cover"
              width={1600}
              height={900}
              layout="responsive"
              itemProp="image"
            />
          )}
        </div>
        <HomeButton />
        <meta itemProp="name" content={title} />
        <meta itemProp="description" content={description} />
        <meta itemProp="image" content={coverImage} />
        {!!tags.length && <meta itemProp="keywords" content={tags.join(",")} />}
      </header>
      <Body className="text-lg text-gray-700 dark:text-gray-200 border-b border-lime-500">
        <article
          className="mb-10"
          itemProp="articleBody"
          dangerouslySetInnerHTML={{
            __html: content,
          }}
        />
        {/* TODO: re-enable once tag pages are implemented
       <footer>
        <Tags tags={tags} />
      </footer> */}
      </Body>
    </div>
  );
};

export const getStaticProps: GetStaticProps<
  PostProps,
  { slug: string }
> = async ({ params }) => ({
  props: await getPost(params?.slug ?? ""),
});

export const getStaticPaths: GetStaticPaths = async () => {
  const posts = await getAllPosts();
  writePostsSpecToFS(posts);

  return {
    paths: posts.map(({ data: { slug } }) => ({ params: { slug } })),
    fallback: false,
  };
};

export default Post;

// src/routes/posts/[slug].svelte
<script context="module">
	import type { Load } from '@sveltejs/kit';

	export const load: Load = async ({ page: { path }, fetch }) => {
		const res = await fetch(`${path}.json`);

		return {
			props: {
				post: await res.json(),
				path
			}
		};
	};
</script>

<script>
	import { onMount } from 'svelte';
	import SvelteSeo from 'svelte-seo';
	import { Body, HomeButton } from '$lib/components';
	import { defaultAuthor, seoData } from '$lib/seoConstants';

	export let post: PostData;
	export let path: string;
	let fullImgPath: string;
	let fullPageUrl: string;

	$: ({
		content,
		meta: { readTime, published, cover, title, description, tags, author = defaultAuthor, date }
	} = post);

	onMount(() => {
		const host = window.location.host;
		const protocol = window.location.protocol;
		const baseUrl = `${protocol}//${host}`;
		fullPageUrl = `${baseUrl}${path}`;
		fullImgPath = `${cover?.includes('http') ? '' : baseUrl}${cover}`;
	});
	$: seo = seoData({
		title,
		description,
		tags,
		canonical: fullPageUrl,
		author,
		type: 'article',
		image: fullImgPath
	});
</script>

<svelte:head>
	<meta name="image" content={fullImgPath} />
</svelte:head>

<SvelteSeo
	{...seo}
	openGraph={{
		...seo.openGraph,
		images: fullImgPath ? [{ url: fullImgPath, alt: 'Article Cover' }] : undefined,
		article: {
			publishedTime: date,
			authors: [author],
			section: tags?.[0],
			tags
		}
	}}
/>

<div itemScope itemType="https://schema.org/TechArticle">
	<header>
		<div class="relative overflow-hidden text-center text-white max-h-cover min-h-cover">
			<div
				class="absolute inset-x-0 bottom-0 z-10 max-w-xl px-6 pb-16 mx-auto text-center md:max-w-3xl xl:max-w-4xl text-shadow-lg"
			>
				<p class="text-sm uppercase">{readTime}</p>
				<h1 itemProp="headline">{title}</h1>
				<p itemProp="datePublished">{published}</p>
			</div>

			<img
				class="filter-blur"
				src={cover}
				alt="Post cover"
				width={1600}
				height={900}
				itemProp="image"
			/>
		</div>
		<HomeButton />
		<meta itemProp="name" content={title} />
		<meta itemProp="description" content={description} />
		<meta itemProp="image" content={fullImgPath} />
		{#if !!tags?.length} <meta itemProp="keywords" content={tags.join(',')} /> {/if}
	</header>
	<Body classes="text-lg text-gray-700 dark:text-gray-200 border-b border-lime-500">
		<article class="mb-10" itemProp="articleBody">{@html content}</article>
		<!-- TODO: re-enable once tag pages are implemented
     <footer>
      <Tags tags={tags} />
    </footer> -->
	</Body>
</div>
