// src/lib/components/Header.svelte
<script>
	export let title: string;
	export let subTitle: string;
	export let subTitleLink: string;
</script>

<header class="mb-10">
	<div
		class="max-w-xl px-6 py-10 mx-auto text-center border-b border-lime-500 md:max-w-3xl xl:max-w-4xl md:py-32"
	>
		<h1 class="text-4xl sm:text-5xl md:text-6xl">{title}</h1>
		<h2>
			{#if subTitleLink}
				<a
					href={subTitleLink}
					class="text-gray-700 dark:text-gray-300 transition duration-500 border-b border-transparent hover:text-gray-800 dark:hover:text-gray-100 hover:border-gray-400"
				>
					{subTitle}
				</a>
			{:else}
				<span class="text-gray-800 dark:text-gray-200">{subTitle}</span>
			{/if}
		</h2>
	</div>
</header>

// components/Header.tsx
import React, { useCallback } from "react";
import Link from "next/link";

const Header: React.FC<{
  title: string;
  subTitle?: string;
  subTitleLink?: string;
}> = ({ title, subTitle, subTitleLink }) => {
  const SubTitleWrapper: React.FC = useCallback(
    subTitleLink
      ? ({ children }) => (
          <Link href={subTitleLink}>
            <a className="text-gray-700 dark:text-gray-300 transition duration-500 border-b border-transparent hover:text-gray-800 dark:hover:text-gray-100 hover:border-gray-400">
              {children}
            </a>
          </Link>
        )
      : ({ children }) => (
          <span className="text-gray-800 dark:text-gray-200">{children}</span>
        ),
    [subTitleLink]
  );
  return (
    <header className="mb-10">
      <div className="max-w-xl px-6 py-10 mx-auto text-center border-b border-lime-500 md:max-w-3xl xl:max-w-4xl md:py-32">
        <h1 className="text-4xl sm:text-5xl md:text-6xl">{title}</h1>
        <h2>
          <SubTitleWrapper>{subTitle}</SubTitleWrapper>
        </h2>
      </div>
    </header>
  );
};

export default Header;
