// src/pages/Index.vue
<template>
  <Layout class="bg-white">
    <main>
      <header>
        <div
          class="max-w-xl md:max-w-3xl xl:max-w-4xl mx-auto text-center px-6 py-10 md:py-32 border-b border-green-500"
        >
          <h1 class="text-4xl sm:text-5xl md:text-6xl font-sans font-bold mb-1">
            <g-link to="/" class="text-black">Ivo Berger</g-link>
          </h1>
          <h5 class="text-xl sm:text-2xl md:text-2xl font-sans mb-1">
            <g-link
              to="/about"
              class="text-gray-600 hover:border-gray-400 border-b border-transparent transition-border-color"
            >About me</g-link>
          </h5>
          <!-- <p
            class="text-gray-700 text-lg sm:text-3xl mt-4"
          >Posts on anything I find interesting, helpful or exciting</p>-->
        </div>
      </header>
      <section>
        <post-item v-for="edge in $page.posts.edges" :key="edge.node.id" :post="edge.node" />
      </section>
      <pagination :info="$page.posts.pageInfo" v-if="$page.posts.pageInfo.totalPages > 1" />
      <site-footer class="py-8 sm:py-16" />
    </main>
  </Layout>
</template>

<script>
import config from "~/.temp/config.js";
import SiteFooter from "@/components/Footer";
import PostItem from "@/components/PostItem";
import Pagination from "@/components/Pagination";

export default {
  components: {
    PostItem,
    Pagination,
    SiteFooter
  },
  metaInfo() {
    return {
      title: this.config.siteName,
      meta: [
        { property: "og:type", content: "website" },
        { property: "og:title", content: this.config.siteName },
        { property: "og:description", content: this.config.siteDescription },
        { property: "og:url", content: this.config.siteUrl },

        { name: "twitter:card", content: "summary_large_image" },
        { name: "twitter:title", content: this.config.siteName },
        { name: "twitter:description", content: this.config.siteDescription }
      ]
    };
  },
  computed: {
    config() {
      return config;
    }
  }
};
</script>

<page-query>
  query Home ($page: Int) {
    posts: allPost (page: $page, perPage: 6) @paginate {
      totalCount
      pageInfo {
        totalPages
        currentPage
      }
      edges {
        node {
          id
          title
          datetime: date (format: "YYYY-MM-DD HH:mm:ss")
          content
          excerpt
          description
          path
          cover
          tags {
            id
            title
            path
          }
        }
      }
    }
  }
</page-query>

// pages/index.tsx
import { getAllPosts } from "lib";
import { compareDesc } from "date-fns";

import React from "react";
import Link from "next/link";
import Head from "next/head";
import type { GetStaticProps } from "next";
import { Header } from "components";

const PostInfo: React.FC<PostMetadata> = ({
  title,
  date,
  description,
  tags,
  slug,
}) => (
  <div className="py-4 text-center border-b border-green-300 group sm:py-10">
    <header className="mb-8 ">
      <time className="mb-2 text-xs text-gray-700 uppercase">{date}</time>
      <Link href="/posts/[slug]" as={`/posts/${slug}`}>
        <a>
          <h3 className="my-0 mb-1">{title}</h3>
        </a>
      </Link>
      <p className="text-sm leading-normal text-gray-700 sm:text-base">
        {tags.length && (
          <>
            in{" "}
            <Link href="/tag/[tag]}" as={`/tag/${tags[0]}`}>
              <a className="text-gray-700 capitalize transition duration-500 border-b border-transparent hover:border-gray-400">
                {tags[0]}
              </a>
            </Link>
          </>
        )}
      </p>
    </header>
    <p className="px-2 text-lg leading-normal text-gray-700 sm:px-4 md:px-10">
      {description}
    </p>
  </div>
);

type HomeProps = { posts: PostMetadata[] };

const Home: React.FC<HomeProps> = ({ posts }) => (
  <>
    <main className="container mx-auto">
      <Head>
        <title>Ivo's Website</title>
        <meta
          name="description"
          content="Main Page with a List of my Blog Posts"
        />
      </Head>
      <Header title="Ivo Berger" subTitle="Stuff I Made" subTitleLink="about" />
      <section className="max-w-3xl px-6 mx-auto mb-10">
        {posts.map((post) => (
          <PostInfo key={post.title} {...post} />
        ))}
      </section>
    </main>
  </>
);

export const getStaticProps: GetStaticProps<HomeProps> = async () => ({
  props: {
    posts: (await getAllPosts())
      .map(({ data }) => data)
      .sort(({ date: dateA }, { date: dateB }) =>
        compareDesc(new Date(dateA), new Date(dateB))
      ),
  },
});

export default Home;
